### ISSUE TITLE
Reconnect after .jep is changed not working

### ISSUE THREAD

**Issue by moltob** [jep-project/jep-python#7]
1. Create connection to backend from Sublime.
2. Let it run for a while, frontend will receive backend alive messages.
3. Edit file covered by .jep.
4. Modify .jep file.

Expected: Frontend shuts down current connection and then reconnects.

Actual: Connection is shut down and stopped:

```
23:03:52 DEBUG         jep.frontend:47        get_connection() Service connector requested for file: D:\Work\jep\test\my.testlang
23:03:52 DEBUG         jep.frontend:57        get_connection() Config file %s changed, need to restart connection.
23:03:52 DEBUG         jep.frontend:163         send_message() Sending message <jep.schema.Shutdown object at 0x0000001D0228EBA8>.
23:03:52 DEBUG         jep.frontend:165         send_message() Sending data b'\x81\xa8_message\xa8Shutdown'.
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:51,786 jep.backend DEBUG: Sending alive message to 1 frontend(s).<<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.backend DEBUG: Received data: b'\x81\xa8_message\xa8Shutdown'<<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.backend DEBUG: Read data in 1 cycles.<<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.protocol DEBUG: Decoded 19 bytes from stream to message <class 'jep.schema.Shutdown'>. 0 bytes left.<<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.backend DEBUG: Received message: <jep.schema.Shutdown object at 0x00000000030294E0><<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.backend.sample INFO: Received shutdown in listener.<<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.backend DEBUG: Frontend requested backend to shut down.<<<
23:03:52 DEBUG         jep.frontend:314 _read_backend_output() [backend] >>>2015-04-11 23:03:52,317 jep.backend INFO: Backend stopped.<<<
23:03:52 DEBUG         jep.frontend:214   _run_disconnecting() Backend process shut down gracefully.
23:03:52 DEBUG         jep.frontend:290             _cleanup() Output reader thread stopped.
```

Upon retry the state is fully corrupted (and the previously mentioned read output of unconnected process leads to exception:

```
23:08:45 DEBUG         jep.frontend:47        get_connection() Service connector requested for file: D:\Work\jep\test\my.testlang
23:08:45 DEBUG         jep.frontend:57        get_connection() Config file %s changed, need to restart connection.
23:08:45 WARNING         jep.frontend:170         send_message() In state State.Disconnected no messages are sent to backend, but received request to send <jep.schema.Shutdown object at 0x0000001D0228E978>.
Traceback (most recent call last):
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\jep.py", line 69, in timeout
    backend_adapter.run()
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\jep.py", line 61, in run
    con.run(datetime.timedelta(seconds=0.1))
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 153, in run
    self._dispatch(endtime - now)
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 158, in _dispatch
    self._state_handler[self.state](duration)
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 203, in _run_disconnecting
    self._read_backend_output()
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 312, in _read_backend_output
    while not self._process_output_reader.queue_.empty():
AttributeError: 'NoneType' object has no attribute 'queue_'
```

**Comment by moltob** [comment]
Cleaned up. Now existing connection is cleanly reused:

```
01:26:51 DEBUG         jep.frontend:43        get_connection() Service connector requested for file: D:\Work\jep\test\my.testlang
01:26:51 DEBUG         jep.frontend:53        get_connection() Config file D:\Work\jep\test\.jep changed, need to renew connection.
01:26:51 DEBUG         jep.frontend:147            reconnect() Reconnecting due to changed service configuration.
01:26:51 DEBUG         jep.frontend:168         send_message() Sending message <jep.schema.Shutdown object at 0x0000004483D16A90>.
01:26:51 DEBUG         jep.frontend:170         send_message() Sending data b'\x81\xa8_message\xa8Shutdown'.
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:50,954 jep.backend DEBUG: Sending alive message to 1 frontend(s).<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend DEBUG: Received data: b'\x81\xa8_message\xa8Shutdown'<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend DEBUG: Read data in 1 cycles.<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.protocol DEBUG: Decoded 19 bytes from stream to message <class 'jep.schema.Shutdown'>. 0 bytes left.<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend DEBUG: Received message: <jep.schema.Shutdown object at 0x0000000001F694E0><<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend.sample INFO: Received shutdown in listener.<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend DEBUG: Frontend requested backend to shut down.<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend INFO: Frontend 43708136 disconnected.<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend INFO: Frontend 44078688 disconnected.<<<
01:26:51 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,157 jep.backend INFO: Backend stopped.<<<
01:26:51 DEBUG         jep.frontend:214   _run_disconnecting() Backend process shut down gracefully.
01:26:51 DEBUG         jep.frontend:291             _cleanup() Output reader thread stopped.
01:26:51 INFO          jep.frontend:296             _cleanup() Disconnected from backend.
01:26:51 DEBUG         jep.frontend:299             _cleanup() Attempting to reconnect.
01:26:51 DEBUG         jep.frontend:114              connect() Starting backend service with command "..\jepenv\Scripts\python.exe ..\..\..\Utilities\Sublime\Data\Packages\jep-python\test\scripts\jep-backend-sample.py" in directory D:\Work\jep\test.
01:26:52 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>2015-04-12 01:26:51,813 jep.backend INFO: Starting backend.<<<
01:26:52 DEBUG         jep.frontend:316 _read_backend_output() [backend] >>>JEP service, listening on port 9001<<<
01:26:52 DEBUG         jep.frontend:309 _parse_port_announcement() Backend announced listening at port 9001.
01:26:52 INFO          jep.frontend:227             _connect() Connected to backend command ..\jepenv\Scripts\python.exe ..\..\..\Utilities\Sublime\Data\Packages\jep-python\test\scripts\jep-backend-sample.py
```
