### ISSUE TITLE
Frontend state inconsistent after execution of erroneous backend call command

### ISSUE THREAD

**Issue by moltob** [jep-project/jep-python#8]
If the .jep file contains a command that cannot be executed by the system, the frontend correctly notices this:

```
23:11:23 DEBUG         jep.frontend:47        get_connection() Service connector requested for file: D:\Work\jep\test\my.testlang
23:11:23 DEBUG         jep.frontend:63        get_connection() Creating new connection.
23:11:23 DEBUG         jep.frontend:116              connect() Starting backend service with command "..\jepenv\Scripts\pythonX.exe ..\..\..\Utilities\Sublime\Data\Packages\jep-python\test\scripts\jep-backend-sample.py" in directory D:\Work\jep\test.
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Utilities\Sublime\sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\jep.py", line 79, in on_query_completions
    res = backend_adapter.request_completion(view, view.file_name(), view.substr(sublime.Region(0, view.size())), locations[0])
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\jep.py", line 26, in request_completion
    con = self._connection(file)
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\jep.py", line 54, in _connection
    con = self.frontend.get_connection(file)
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 64, in get_connection
    connection = self._connect(service_config)
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 74, in _connect
    connection.connect()
  File "D:\Utilities\Sublime\Data\Packages\jep-sublime\..\jep-python\jep\frontend.py", line 133, in connect
    universal_newlines=True)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

The resulting state of the connector is fully invalid. However, upon rerequest by the plugin, the frontend:
* Reuses the invalid connection.
* Does not attempt to reconnect.

So nothing really happens:

```
23:12:10 DEBUG         jep.frontend:47        get_connection() Service connector requested for file: D:\Work\jep\test\my.testlang
23:12:10 DEBUG         jep.frontend:61        get_connection() Using existing connection.
```

The desired behavior is in either way to really retry to connect to the backend, either with the existing or with a new connector.

**Comment by moltob** [comment]
Now properly reattempted.
